### PR TITLE
Add FR locales

### PR DESCRIPTION
**Pull request by lucasmichot**
Add french locales

### CODE REVIEW

**Comment by lucasmichot** [comment]
@julman99 any news on that ?

**Comment by julman99** [comment]
hi @lucasmichot, thanks for suggesting this. Can you also add the new entries I defined [here](https://github.com/julman99/whatsapp-chrome/blob/master/_locales/en/messages.json)

**Comment by lucasmichot** [comment]
Done @julman99

**Comment by julman99** [comment]
Awesome thanks!

**Comment by julman99** [comment]
Deployed to the store in version 0.8.0

**Comment by lucasmichot** [comment]
Nice!

**Pull request merged**
